config/routes.rb
Rails.application.routes.draw do
devise_for :users
 root to: 'user#top'
 resources :books, only: [:new, :create, :index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user
attachment :bo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

def new
  @book = Book.new
end

def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  @book.save
  redirect_to books_path
end

def index
  @books = Book.all
end

def show
  @book = Book.find(params[:id])
end

def destroy
  @book = Book.find(params[:id])
  @book.destroy
  redirect_to books_path
end

private

def book_params
  params.require(:book).permit(:title, :body)
end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <P>user-icon</P>
  <% end %>
  <p><%= book.title %></p>
  <p><%= book.body %></p>
</div>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Option</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h1>Book detail</h1>
<div class="post-body">
  <p>user-icon</p>
  <p><%= @book.title %></p>
  <p><%= @book.body %></p>
  <% if @book.user == current_user %>
    <%= link_to "delete", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <li>
      <%= link_to 'NewBook', new_book_path %>
    </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "rogin", new_user_session_path %>
      </li>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/user/top.html.erb
<h1>welcome to <string>Bookers!!</string></h1>
<p>in <string>Bookers</string>,</p>
<p>you can share and exchange your opinions, inpressions, and emotions</p>
<p>about various books!</p>

<a>login </a>
<a>sign up</a>